# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [ ]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [10]:
array = np.random.random([3,4])

print(array)

print("NumPy Version:", np.__version__)
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)


[[0.99695993 0.32615686 0.55915806 0.52014571]
 [0.39533571 0.15284596 0.98659621 0.00929952]
 [0.43154348 0.01682433 0.65612046 0.50705293]]
NumPy Version: 2.1.3
(3, 4)
2
12
float64


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [11]:
a = np.random.random([2,3,5])



### 4. Print a.


In [52]:
print(a)

print(a.size)
print(a.shape)
print(a.ndim)


[[[0.83007788 0.37034877 0.81099662 0.86822579 0.94200395]
  [0.02517501 0.29592376 0.08065985 0.68495919 0.92327292]
  [0.26370205 0.88276    0.88621416 0.25237807 0.07764669]]

 [[0.61866969 0.46000657 0.49349041 0.61525597 0.14333508]
  [0.87890508 0.8525677  0.83852918 0.17030796 0.96738743]
  [0.10983363 0.49607825 0.31756818 0.73512813 0.30858739]]]
30
(2, 3, 5)
3


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [16]:
b = np.ones([5,2,3])



### 6. Print b.


In [14]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
if a.size == b.size:
    print("Both arrays have the same size")
else:
    print("Both arrays do not have the same size")


Both arrays have the same size



### 8. Are you able to add a and b? Why or why not?


In [19]:
#NO, because both arrays same size but shapes. It does not accept that broadcast rule.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
c = b.T  #first method - short version

print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [40]:
c = b.transpose(1,2,0)  #second method

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
d = a + c

print(d)

print(d.shape)
print(d.size)
print(d.ndim)


[[[1.83007788 1.37034877 1.81099662 1.86822579 1.94200395]
  [1.02517501 1.29592376 1.08065985 1.68495919 1.92327292]
  [1.26370205 1.88276    1.88621416 1.25237807 1.07764669]]

 [[1.61866969 1.46000657 1.49349041 1.61525597 1.14333508]
  [1.87890508 1.8525677  1.83852918 1.17030796 1.96738743]
  [1.10983363 1.49607825 1.31756818 1.73512813 1.30858739]]]
(2, 3, 5)
30
3



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:

print(a)

print(d)


#The values in the array d are higher than the values of array a by 1 but are in the same order.

# print((a+d).size)
# print((a+d).shape)
# print((a+d).ndim)


[[[0.83007788 0.37034877 0.81099662 0.86822579 0.94200395]
  [0.02517501 0.29592376 0.08065985 0.68495919 0.92327292]
  [0.26370205 0.88276    0.88621416 0.25237807 0.07764669]]

 [[0.61866969 0.46000657 0.49349041 0.61525597 0.14333508]
  [0.87890508 0.8525677  0.83852918 0.17030796 0.96738743]
  [0.10983363 0.49607825 0.31756818 0.73512813 0.30858739]]]
[[[1.83007788 1.37034877 1.81099662 1.86822579 1.94200395]
  [1.02517501 1.29592376 1.08065985 1.68495919 1.92327292]
  [1.26370205 1.88276    1.88621416 1.25237807 1.07764669]]

 [[1.61866969 1.46000657 1.49349041 1.61525597 1.14333508]
  [1.87890508 1.8525677  1.83852918 1.17030796 1.96738743]
  [1.10983363 1.49607825 1.31756818 1.73512813 1.30858739]]]



### 12. Multiply a and c. Assign the result to e.


In [51]:
e = a * c

print(e)

print(e.size)
print(e.shape)
print(e.ndim)


[[[0.83007788 0.37034877 0.81099662 0.86822579 0.94200395]
  [0.02517501 0.29592376 0.08065985 0.68495919 0.92327292]
  [0.26370205 0.88276    0.88621416 0.25237807 0.07764669]]

 [[0.61866969 0.46000657 0.49349041 0.61525597 0.14333508]
  [0.87890508 0.8525677  0.83852918 0.17030796 0.96738743]
  [0.10983363 0.49607825 0.31756818 0.73512813 0.30858739]]]
30
(2, 3, 5)
3




### 13. Does e equal to a? Why or why not?


In [ ]:
# YES, a ie equal to a, as both their size, shapes and dimensions match.





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [59]:
d_max = np.max(d)

d_min = np.min(d)

d_mean = np.mean(d)


print("max value is d is :", d_max)

print("min value of d is :", d_mean)

print("mean value of d is :", d_min)



max value is d is : 1.9673874328088092
min value of d is : 1.5399998455478525
mean value of d is : 1.025175005735183



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [69]:
f = np.empty([2,3,5])

# or f = np.empty_like(d) - entering the array name directly instead of shaoe of the array.

print(f)


[[[1.83007788 1.37034877 1.81099662 1.86822579 1.94200395]
  [1.02517501 1.29592376 1.08065985 1.68495919 1.92327292]
  [1.26370205 1.88276    1.88621416 1.25237807 1.07764669]]

 [[1.61866969 1.46000657 1.49349041 1.61525597 1.14333508]
  [1.87890508 1.8525677  1.83852918 1.17030796 1.96738743]
  [1.10983363 1.49607825 1.31756818 1.73512813 1.30858739]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [79]:
# max value is d is : 1.9673874328088092
# min value of d is : 1.5399998455478525
# mean value of d is : 1.025175005735183

print(d)

# f = np.where(((d>d_min) & (d <d_mean)),25,f)
#np.where((d>d_min and d <d_mean),25)
#print(f)
#d_min = np.min(d)  # Ensure scalar value
#d_max = np.max(d)  # Ensure scalar value
#d_mean = np.mean(d)  # Ensure scalar value

for i in range(2):
    for j in range(3):
        for k in range(5):
            d_value = d[i,j,k]
            if d_min < d_value < d_mean:
                f[i, j, k] = 25
            elif d_value == d_mean:
                f[i, j, k] = 50
            elif d_mean < d_value < d_max:
                f[i, j, k] = 75
            elif d_value == d_min:
                f[i, j, k] = 0
            elif d_value == d_max:
                f[i, j, k] = 100
print(f)



[[[1.83007788 1.37034877 1.81099662 1.86822579 1.94200395]
  [1.02517501 1.29592376 1.08065985 1.68495919 1.92327292]
  [1.26370205 1.88276    1.88621416 1.25237807 1.07764669]]

 [[1.61866969 1.46000657 1.49349041 1.61525597 1.14333508]
  [1.87890508 1.8525677  1.83852918 1.17030796 1.96738743]
  [1.10983363 1.49607825 1.31756818 1.73512813 1.30858739]]]
[[[ 75.  25.  75.  75.  75.]
  [  0.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  25.  25.  75.  25.]
  [ 75.  75.  75.  25. 100.]
  [ 25.  25.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
# Yes, the f array is polpulated according to the conditions mentioned.


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [92]:


f_strings = np.empty_like(d, dtype='<U1')  

for i in range(2):
    for j in range(3):
        for k in range(5):
            d_value = d[i, j, k]
            if d_min < d_value < d_mean:
                f[i, j, k] = 'B'
            elif d_value == d_mean:
                f[i, j, k] = 'C'
            elif d_mean < d_value < d_max:
                f[i, j, k] = 'D'
            elif d_value == d_min:
                f[i, j, k] = 'A'
            elif d_value == d_max:
                f[i, j, k] = 'E'

print(f)


[[['D' 'B' 'D' 'D' 'D']
  ['A' 'B' 'B' 'D' 'D']
  ['B' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'E']
  ['B' 'B' 'B' 'D' 'B']]]
